<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Constellation.Application\Constellation.Application.csproj" />
    <ProjectReference Include="..\Constellation.Domain\Constellation.Domain.csproj" />
    <ProjectReference Include="..\Constellation.Infrastructure\Constellation.Infrastructure.csproj" />
  </ItemGroup>

</Project>
